import react from "react";
function Compo2() {
  return (
    <div>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
      <h1>hello i am compo2</h1>
    </div>
  );
}

export default Compo2;
